version: '2'
services:
  webserver:
    container_name: web-server
    build:
      context: .
      dockerfile: ./web/Dockerfile
    networks:
      ctf-private:          
    ports:
      - "1080:80"
    restart: unless-stopped
  webserver2:
    container_name: web-server2
    build:
      context: .
      dockerfile: ./web2/Dockerfile
    networks:
      ctf-private:          
        aliases:
          - internal.evilcorp.org 
    ports:
      - "2080:80"
    restart: unless-stopped
  ssh:
    container_name: ssh
    build:
      context: .
      dockerfile: ./ssh/Dockerfile
      args:
        CTF_USER_ARG: ${CTF_USER}
        FLAG_ONE_CONTENT_ARG: ${FLAG_ONE_CONTENT}
        SSH_TARGET_2_PRIVATE_IP_ARG: ${SSH_TARGET_2_PRIVATE_IP}
    ports:
      - "2222:22"           
      - "6379:6379"        
    networks:
      ctf-private:
        ipv4_address: ${SSH_TARGET_1_PRIVATE_IP} 
    restart: unless-stopped

  ssh2:
    container_name: ssh2
    build:
      context: .
      dockerfile: ./ssh2/Dockerfile
      args: 
        CTF_USER_ARG: ${CTF_USER}
        FLAG_TWO_CONTENT_ARG: ${FLAG_TWO_CONTENT}
    networks:
      ctf-private:
        ipv4_address: ${SSH_TARGET_2_PRIVATE_IP} 
    privileged: true
#    ports:
#      - "2022:22"
    restart: unless-stopped
    read_only: true
    volumes:
      - /tmp:/tmp:rw
      - /var/tmp:/var/tmp:rw
      - /var/log:/var/log:rw
      - /var/run:/var/run:rw
      - /var/spool/cron:/var/spool/cron:rw
      - /dev/shm:/dev/shm:rw
networks:
  ctf-private:
    driver: bridge
    ipam:
      config:
        - subnet: ${CTF_PRIVATE_SUBNET} 
